defaults:
  - _self_
  - env: "phylo_gfn"
  - algorithm: "fldb"

# Number of parallel environments
num_envs: 32

env_wrapper:
  _target_: "gfn_maxent_rl.envs.wrappers.RewardCorrection"
  alpha: 1.0

exploration:
  # Minimum value of epsilon-exploration
  min_exploration: 0.0

  # Number of steps for warming up exploration
  warmup: 50_000  # 100_000 / 2

# Learning rate
lr1:
  _target_: optax.warmup_cosine_decay_schedule
  init_value: 0.0
  peak_value: 3e-4
  warmup_steps: 5000
  decay_steps: 95000
  end_value: 1e-5

lr2:
  _target_: optax.warmup_cosine_decay_schedule
  init_value: 0.0
  peak_value: 3e-4
  warmup_steps: 5000
  decay_steps: 95000
  end_value: 1e-5

# Batch size
batch_size: 128

# Number of iterations
num_iterations: 100_000

# Random seed
seed: 0

# Frequency for logging
log_every: 500

# Frequency for evaluation
evaluation_every: 500

# Evaluation batch size
evaluation_batch_size: 32

# Number of terminal states to sample for correlation metrics
n_eval: 32

# Name of the group for Wandb
group_name: "default_1"
experiment_name: "default"

reward_correction: false

# Upload the logs to Wandb, mode="disabled" or "online"
upload: "online"
